name: build-exe

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ./installResources.ps1
      - name: Build exe
        run: pyinstaller --onefile converter.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: converter-exe
          path: dist/converter.exe
